Add controllers
steelzhi/java-shareit pull request #1
Opened 2023-05-21 07:39 UTC by steelzhi

2023-05-22 07:00 UTC, mikita95 requested changes
Все сделано отлично. Нужно лишь поправить пару моментов

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +Хотел у Вас спросить: т.к. в этом модуле мы используем структуру не по типам классов, а по фичам, то нужно ли в папке
Отличный вопрос. Какого-то правила нет :) Здесь как вам кажется удобнее и понятнее. Единственное, что лучше тогда сделать везде единообразно. В целом, действительно, сейчас по одному классу на пакет может быть немного избыточно, так что можно было бы и не делать вложенные пакеты, но в дальнейшем проект вырастит, и придется добавить еще классов в пакеты, тогда уже удобнее использовать вложенные

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Раз вы сделали класс ItemMapper бином спринга, то здесь не нужно использовать static, либо нужно класс не делать бином. Нужно выбрать что-то одно :)

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemDtoRepository.java
> +        if (items.get(userId) == null) {
Лучше использовать метод containsKey - так понятнее и аккуратнее

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/utility/Checker.java
> +public final class Checker {
Создавать такие утилитные классы "для всего" - обычно не очень удачно архитектурное решение, так сложнее тестировать код, разделять зависимости и т.д. Лучше все же валидацию поместить либо в сервисы с логикой, либо сделать отдельные классы в соответствующих пакетах

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemDtoRepository.java
> +    public ItemDto getItemDto(Long itemId) {
Сейчас этот метод работает за O(n), что долго. Лучше добавить в класс еще одну мапу itemId -> Item, и использовать ее

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<ItemDto> allItemsDto = itemRepository.getAllItemsDto();
Этот кусок кода можно было бы переписать в функциональном виде:
```
return itemRepository.getAllItemsDto().stream.map(...).toList();
```
Так было бы чуть короче

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> + * TODO Sprint add-controllers.
Комментарий можно убрать

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> + * TODO Sprint add-controllers.
Комментарий можно убрать

2023-05-22 07:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    //метод, необходимый для unit-тестирования
В целом этот метод полезен не только при юнит-тестировании, можно не писать такой комментарий

2023-05-22 17:33 UTC, steelzhi commented
Никита, здравствуйте.
Спасибо за ревью! Замечания исправил - проверьте, пожалуйста.

2023-05-22 17:33 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +Хотел у Вас спросить: т.к. в этом модуле мы используем структуру не по типам классов, а по фичам, то нужно ли в папке
Раз в следующих ТЗ проект вырастит, то для единообразия добавил пакеты в фичи booking и request.

2023-05-22 17:33 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Да, точно - экземпляр ItemMapper все равно же будет создан. Убрал модификатор static из метода.

2023-05-22 17:33 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemDtoRepository.java
> +        if (items.get(userId) == null) {
Исправил.

2023-05-22 17:33 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/utility/Checker.java
> +public final class Checker {
Понятно. Исправил - перенес все методы проверки на уровень сервисов.

2023-05-22 17:33 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemDtoRepository.java
> +    public ItemDto getItemDto(Long itemId) {
Исправил.

2023-05-22 17:34 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<ItemDto> allItemsDto = itemRepository.getAllItemsDto();
Переделал.

2023-05-22 17:34 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> + * TODO Sprint add-controllers.
Убрал.

2023-05-22 17:34 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> + * TODO Sprint add-controllers.
Убрал.

2023-05-22 17:34 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    //метод, необходимый для unit-тестирования
Комментарий убрал.

2023-05-23 17:47 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-05-24 06:29 UTC, merged