Add bookings
steelzhi/java-shareit pull request #2
Opened 2023-06-06 15:56 UTC by steelzhi

Добавление в приложение функций бронирования и комментирования

2023-06-07 14:32 UTC, mikita95 requested changes
Все сделано хорошо. Оставил несколько замечаний

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                 @RequestHeader("X-Sharer-User-Id") Long userId) {
Можно использовать примитивный тип long, user id не может быть null

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +
Лишняя строка

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "SELECT * " +
Лучше native query не использовать везде где можно) Если например, придется переходить на другую базу данных, то и все запросы нужно будет переносить. Здесь же можно воспользоваться "магией" спринга, например, просто написав имя метода как findByBooker_Id, спринг сам сможет сгенерировать нужный запрос.
Также вместо нативного запроса, можно использовать JPQL - это более универсальная вещь. Нативные запросы нужно, чтобы использовать специфические фичи конкретной базы данных в основном

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    Booking createBooking(ru.practicum.shareit.booking.dto.BookingDto bookingDto, Long userId);
Здесь можно вынести dto в импорт, чтобы не писать полный путь

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Booking> bookings = bookingRepository.findAll();
Проверять существование лучше более эффективным способом, запрашивать все из базы - это дорого

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            System.out.println(user);
Лучше писать в лог, в готовом коде не должно быть System.out.println

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
Нужно искать более эффективно, просто обращаясь в базу по id

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    e.printStackTrace();
printStackTrace не должно быть, нужно писать в лог

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            switch (bookingStatus) {
Здесь нужно использовать enum, так эффективнее

2023-06-07 14:32 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public CommentDto postComment(Long itemId, Comment comment, Long userId) {
Лучше исполнять операции, состоящие из нескольких запросов к базе, в транзакции (аннотация Transactional) - так вы гарантируете корректную видимость данных. Аналогично во всем проекте.

2023-06-08 05:32 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                 @RequestHeader("X-Sharer-User-Id") Long userId) {
Исправил.

2023-06-08 05:33 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +
Исправил.

2023-06-08 06:25 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "SELECT * " +
Понял, спасибо. Исправил.

2023-06-08 06:25 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    Booking createBooking(ru.practicum.shareit.booking.dto.BookingDto bookingDto, Long userId);
Полный путь случайно прицепился. Исправил.

2023-06-08 07:05 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Booking> bookings = bookingRepository.findAll();
Понятно. Исправил (в этом сервисе, а также в сервисе Item).

2023-06-08 07:07 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            System.out.println(user);
Оптимизировал метод посредством Optional.

2023-06-08 07:10 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
Исправил.

2023-06-08 07:26 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    e.printStackTrace();
Это лишняя строка, забыл удалить. Исправил.

2023-06-08 07:29 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            switch (bookingStatus) {
Исправил.

2023-06-08 08:13 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public CommentDto postComment(Long itemId, Comment comment, Long userId) {
Расставил соответствующую аннотацию методам, в которых происходит несколько обращений к БД. Проверьте, пожалуйста.

2023-06-08 08:23 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
> Все сделано хорошо. Оставил несколько замечаний

Никита, здравствуйте.
Спасибо за ревью - увидел много мест, где можно было бы сделать оптимальнее) Исправления внес - проверьте, пожалуйста.

2023-06-08 08:24 UTC, steelzhi commented
Никита, здравствуйте.
Спасибо за ревью - увидел много мест, где можно было бы сделать оптимальнее) Исправления внес - проверьте, пожалуйста.

2023-06-09 09:40 UTC, mikita95 approved these changes
Все сделано хорошо. Можно мержить пул-реквест

2023-06-09 09:40 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +Никита, здравствуйте.
В этом задании юнит-тесты не требуются. Можно в тестах подложить нужный конфиг спринга, используя например, аннотацию TestConfiguration. Можно обратиться к наставнику, за более подробной информацией:)

2023-06-09 10:32 UTC, merged