Add item requests
steelzhi/java-shareit pull request #3
Opened 2023-06-17 16:50 UTC by steelzhi

Добавить функционал запросов вещей. Добавить тесты для всех слоев всех сущностей.

2023-06-17 17:53 UTC, steelzhi commented
Никита, здравствуйте.
Задание выполнил - проверьте, пожалуйста.

2023-06-18 09:05 UTC, steelzhi commented
Никита, здравствуйте.
Задание выполнил - проверьте, пожалуйста.

2023-06-18 14:55 UTC, mikita95 requested changes
Все сделано хорошо. Правда нужно немного разделить dto от модели хранения

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +                                       @RequestBody ItemRequest itemRequest) {
Здесь нужно использовать dto, а не класс модели хранения данных :)

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +/*    @ExceptionHandler
Не должно быть закомментированного кода - лучше удалить

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public Item postItem(@Valid @RequestBody Item item, @RequestHeader("X-Sharer-User-Id") long userId) {
Контроллер должно работать только с dto, а не с классами модели хранения данных

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.patchItem(itemId, item, userId);
Контроллер должно работать только с dto, а не с классами модели хранения данных

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<Item> searchItems(@PathParam("text") String text,
Контроллер должно работать только с dto, а не с классами модели хранения данных

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
>  @Component
Если вы сделали класс с static методами, то эти мапперы не должны быть бинами спринга, достаточно просто вызывать static методы. Аналогично во всем проекте

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    public ItemRequest postItemRequest(@RequestHeader("X-Sharer-User-Id") long userId,
Контроллер должн работать только с dto, а не с классами модели хранения данных

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private List<Item> items;
dto не должно знать о модели хранения. Нужно использовать тоже dto

2023-06-18 14:55 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private User requester;
dto не должно знать о модели хранения. Нужно использовать тоже dto

2023-06-20 10:56 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +                                       @RequestBody ItemRequest itemRequest) {
Исправил.

2023-06-20 10:56 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +/*    @ExceptionHandler
Почистил.

2023-06-20 10:56 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public Item postItem(@Valid @RequestBody Item item, @RequestHeader("X-Sharer-User-Id") long userId) {
Исправил.

2023-06-20 10:57 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.patchItem(itemId, item, userId);
Исправил.

2023-06-20 10:57 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<Item> searchItems(@PathParam("text") String text,
Исправил.

2023-06-20 10:57 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
>  @Component
Понятно. Убрал аннотацию @Component у мапперов.

2023-06-20 10:57 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    public ItemRequest postItemRequest(@RequestHeader("X-Sharer-User-Id") long userId,
Исправил.

2023-06-20 10:57 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private List<Item> items;
Исправил.

2023-06-20 10:57 UTC, steelzhi commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private User requester;
Исправил.

2023-06-20 11:00 UTC, steelzhi commented
Никита, здравствуйте.
Я разделил модель и dto, как Вы сказали: теперь на входе и на выходе у всех контроллеров и сервисов только dto, а модель используется только репозиториями. Спасибо за ревью.

2023-06-20 11:39 UTC, steelzhi commented
Никита, здравствуйте.
Я разделил модель и dto, как Вы сказали: теперь на входе и на выходе у всех контроллеров и сервисов только dto, а модель используется только репозиториями. Спасибо за ревью.

2023-06-21 10:01 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-06-21 10:01 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +public class BookingDtoIn {
Можно было бы назвать не In и Out, а Request и Response :)

2023-06-21 10:01 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingDtoOutForController> getAllBookingDtosForUserItems(
В название метода можно не включать слово dto :) Ведь имя метода отображает функциональность, а не технические условия

2023-06-21 10:19 UTC, merged